#!/usr/bin/env python3
"""Multi-tenant provisioning for HERMES_HOME profiles.

Each tenant gets a fully isolated HERMES_HOME under ``root_dir/{tenant_id}/``
with its own config.yaml, .env, skills/, sessions/, memory/, and feedback/.
Domain-aware model defaults are applied automatically.

Usage:
    python examples/lunark/multi_tenant.py create --id legal-team --name "Legal Team" --domain legal
    python examples/lunark/multi_tenant.py list
    python examples/lunark/multi_tenant.py status legal-team
    python examples/lunark/multi_tenant.py create-demo
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional


# ---------------------------------------------------------------------------
# Domain model defaults
# ---------------------------------------------------------------------------

# Maps domain -> (simple_qa_model, tool_use_model)
DOMAIN_MODELS: dict[str, tuple[str, str]] = {
    "legal":     ("Qwen3.5-27B", "Qwen3-32B"),
    "medical":   ("Qwen3.5-27B", "Qwen3-32B"),
    "ecommerce": ("Qwen3.5-27B", "Qwen3-32B"),
    "default":   ("Qwen3.5-27B", "Qwen3-32B"),
}

# Skills relevant to each domain, drawn from a shared pool.
# These are folder names that might exist under a shared skills directory.
DOMAIN_SKILLS: dict[str, list[str]] = {
    "legal":     ["document-search", "summarize", "citation-check"],
    "medical":   ["document-search", "summarize", "drug-lookup"],
    "ecommerce": ["product-search", "order-lookup", "summarize"],
    "default":   ["summarize"],
}

DEFAULT_ROOT = os.path.join(os.path.expanduser("~"), ".hermes", "tenants")


# ---------------------------------------------------------------------------
# Dataclass
# ---------------------------------------------------------------------------

@dataclass
class TenantConfig:
    """Configuration for a single tenant profile."""

    tenant_id: str
    tenant_name: str
    domain: str = "default"
    # Populated automatically from DOMAIN_MODELS if not supplied
    model_preferences: dict[str, str] = field(default_factory=dict)
    # Skill bundle names to provision for this tenant
    skill_bundles: list[str] = field(default_factory=list)
    # When True the tenant's memory directory is kept strictly private
    memory_isolation: bool = True
    # Optional: lunark API key override (falls back to env LUNARK_API_KEY)
    api_key: str = ""
    # Optional: lunark base URL override
    base_url: str = "https://llm.lunark.ai/v1"

    def __post_init__(self) -> None:
        qa_model, tool_model = DOMAIN_MODELS.get(self.domain, DOMAIN_MODELS["default"])
        if not self.model_preferences:
            self.model_preferences = {
                "simple_qa": qa_model,
                "tool_use":  tool_model,
            }
        if not self.skill_bundles:
            self.skill_bundles = DOMAIN_SKILLS.get(self.domain, DOMAIN_SKILLS["default"])


# ---------------------------------------------------------------------------
# Config template
# ---------------------------------------------------------------------------

CONFIG_TEMPLATE = """\
# Auto-generated by examples/lunark/multi_tenant.py — do not hand edit
# Tenant: {tenant_name} ({tenant_id})  Domain: {domain}
model:
  default: {default_model}
  tool_use: {tool_model}
  provider: lunark
  base_url: {base_url}
  api_key: {api_key}
providers: {{}}
fallback_providers: []
toolsets: [hermes-cli]
agent:
  max_turns: 60
  reasoning_effort: medium
  tool_use_enforcement: auto
tenant:
  id: {tenant_id}
  name: {tenant_name}
  domain: {domain}
  memory_isolation: {memory_isolation}
"""


# ---------------------------------------------------------------------------
# Core provisioning
# ---------------------------------------------------------------------------

def provision_tenant(config: TenantConfig, root_dir: str = DEFAULT_ROOT) -> Path:
    """Provision an isolated HERMES_HOME for *config* under *root_dir*.

    Creates:
        {root_dir}/{tenant_id}/
            config.yaml
            .env
            skills/
            sessions/
            memory/
            feedback/

    Returns the Path to the provisioned tenant directory.
    """
    tenant_dir = Path(root_dir) / config.tenant_id
    tenant_dir.mkdir(parents=True, exist_ok=True)

    # Sub-directories that form a complete HERMES_HOME
    for sub in ("skills", "sessions", "memory", "feedback"):
        (tenant_dir / sub).mkdir(exist_ok=True)

    api_key = config.api_key or os.environ.get("LUNARK_API_KEY", "vllm-local")

    # Write config.yaml
    config_content = CONFIG_TEMPLATE.format(
        tenant_id=config.tenant_id,
        tenant_name=config.tenant_name,
        domain=config.domain,
        default_model=config.model_preferences["simple_qa"],
        tool_model=config.model_preferences["tool_use"],
        base_url=config.base_url,
        api_key=api_key,
        memory_isolation=str(config.memory_isolation).lower(),
    )
    (tenant_dir / "config.yaml").write_text(config_content)

    # Write .env with tenant-specific settings
    env_lines = [
        f"LUNARK_API_KEY={api_key}",
        f"HERMES_TENANT_ID={config.tenant_id}",
        f"HERMES_TENANT_DOMAIN={config.domain}",
        f"HERMES_HOME={tenant_dir}",
    ]
    if config.memory_isolation:
        env_lines.append(f"HERMES_MEMORY_PATH={tenant_dir / 'memory'}")
    (tenant_dir / ".env").write_text("\n".join(env_lines) + "\n")

    # Copy domain-relevant skills from a shared pool when available
    shared_pool = Path(root_dir) / "_shared_skills"
    if shared_pool.is_dir():
        tenant_skills_dir = tenant_dir / "skills"
        for bundle_name in config.skill_bundles:
            src = shared_pool / bundle_name
            dst = tenant_skills_dir / bundle_name
            if src.is_dir() and not dst.exists():
                shutil.copytree(src, dst)

    # Record provisioning metadata
    meta = {
        "tenant_id": config.tenant_id,
        "tenant_name": config.tenant_name,
        "domain": config.domain,
        "provisioned_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"),
        "model_preferences": config.model_preferences,
        "skill_bundles": config.skill_bundles,
        "memory_isolation": config.memory_isolation,
    }
    (tenant_dir / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")

    return tenant_dir


# ---------------------------------------------------------------------------
# Query helpers
# ---------------------------------------------------------------------------

def list_tenants(root_dir: str = DEFAULT_ROOT) -> list[dict]:
    """Return a list of provisioned tenant metadata dicts sorted by tenant_id."""
    root = Path(root_dir)
    if not root.is_dir():
        return []
    tenants = []
    for entry in sorted(root.iterdir()):
        if entry.name.startswith("_") or not entry.is_dir():
            continue
        meta_file = entry / "meta.json"
        if meta_file.exists():
            tenants.append(json.loads(meta_file.read_text()))
    return tenants


def tenant_status(root_dir: str, tenant_id: str) -> Optional[dict]:
    """Return a status dict for *tenant_id*, or None if not found.

    Status fields:
        skills_count   — number of skill bundles installed
        session_count  — number of session files
        memory_size_kb — total size of the memory directory in kilobytes
        last_active    — ISO timestamp of most recently modified file, or None
    """
    tenant_dir = Path(root_dir) / tenant_id
    if not tenant_dir.is_dir():
        return None

    meta_file = tenant_dir / "meta.json"
    meta: dict = json.loads(meta_file.read_text()) if meta_file.exists() else {}

    skills_dir = tenant_dir / "skills"
    skills_count = sum(1 for p in skills_dir.iterdir() if p.is_dir()) if skills_dir.is_dir() else 0

    sessions_dir = tenant_dir / "sessions"
    session_count = sum(1 for p in sessions_dir.iterdir() if p.is_file()) if sessions_dir.is_dir() else 0

    memory_dir = tenant_dir / "memory"
    memory_size_kb = 0
    if memory_dir.is_dir():
        memory_size_kb = sum(p.stat().st_size for p in memory_dir.rglob("*") if p.is_file()) // 1024

    # Most recently modified file anywhere in the tenant tree
    last_mtime: Optional[float] = None
    for p in tenant_dir.rglob("*"):
        if p.is_file():
            mtime = p.stat().st_mtime
            if last_mtime is None or mtime > last_mtime:
                last_mtime = mtime

    last_active = (
        datetime.fromtimestamp(last_mtime, tz=timezone.utc).isoformat().replace("+00:00", "Z")
        if last_mtime is not None
        else None
    )

    return {
        **meta,
        "tenant_dir": str(tenant_dir),
        "skills_count": skills_count,
        "session_count": session_count,
        "memory_size_kb": memory_size_kb,
        "last_active": last_active,
    }


# ---------------------------------------------------------------------------
# Demo tenants
# ---------------------------------------------------------------------------

DEMO_TENANTS: list[TenantConfig] = [
    TenantConfig(tenant_id="legal-team",    tenant_name="Legal Team",    domain="legal"),
    TenantConfig(tenant_id="medical-team",  tenant_name="Medical Team",  domain="medical"),
    TenantConfig(tenant_id="ecommerce-bot", tenant_name="Ecommerce Bot", domain="ecommerce"),
]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def cmd_create(args: argparse.Namespace) -> None:
    config = TenantConfig(
        tenant_id=args.id,
        tenant_name=args.name,
        domain=args.domain,
    )
    tenant_dir = provision_tenant(config, root_dir=args.root)
    print(f"Provisioned tenant '{config.tenant_id}' at {tenant_dir}")
    print(f"  Domain:  {config.domain}")
    print(f"  QA model:   {config.model_preferences['simple_qa']}")
    print(f"  Tool model: {config.model_preferences['tool_use']}")
    print(f"  Skills:  {', '.join(config.skill_bundles) or '(none)'}")
    print(f"\nTo use:  HERMES_HOME={tenant_dir} hermes chat -q 'hello'")


def cmd_list(args: argparse.Namespace) -> None:
    tenants = list_tenants(root_dir=args.root)
    if not tenants:
        print(f"No tenants found under {args.root}")
        return
    print(f"\n{'TENANT ID':<22} {'NAME':<22} {'DOMAIN':<12} PROVISIONED")
    print("-" * 80)
    for t in tenants:
        print(
            f"  {t.get('tenant_id', ''):<20} "
            f"{t.get('tenant_name', ''):<22} "
            f"{t.get('domain', ''):<12} "
            f"{t.get('provisioned_at', '')}"
        )
    print()


def cmd_status(args: argparse.Namespace) -> None:
    status = tenant_status(root_dir=args.root, tenant_id=args.tenant_id)
    if status is None:
        print(f"Tenant '{args.tenant_id}' not found under {args.root}", file=sys.stderr)
        sys.exit(1)
    print(f"\nStatus for tenant: {status.get('tenant_id')} ({status.get('tenant_name')})")
    print(f"  Domain:         {status.get('domain')}")
    print(f"  Directory:      {status.get('tenant_dir')}")
    print(f"  Skills:         {status.get('skills_count')} bundle(s)")
    print(f"  Sessions:       {status.get('session_count')} file(s)")
    print(f"  Memory:         {status.get('memory_size_kb')} KB")
    print(f"  Last active:    {status.get('last_active') or 'never'}")
    print(f"  Provisioned at: {status.get('provisioned_at', 'unknown')}")
    print()


def cmd_create_demo(args: argparse.Namespace) -> None:
    print(f"Creating 3 demo tenants under {args.root} ...\n")
    for config in DEMO_TENANTS:
        tenant_dir = provision_tenant(config, root_dir=args.root)
        print(f"  {config.tenant_id:<22} -> {tenant_dir}")
    print("\nDone. Run `python multi_tenant.py list` to see all tenants.")


def main() -> None:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--root",
        default=DEFAULT_ROOT,
        help=f"Root directory for tenant profiles (default: {DEFAULT_ROOT})",
    )
    sub = parser.add_subparsers(dest="command", metavar="COMMAND")
    sub.required = True

    # create
    p_create = sub.add_parser("create", help="Provision a new tenant")
    p_create.add_argument("--id",     required=True, help="Unique tenant identifier (e.g. legal-team)")
    p_create.add_argument("--name",   required=True, help="Human-readable tenant name")
    p_create.add_argument("--domain", default="default",
                          choices=list(DOMAIN_MODELS.keys()),
                          help="Domain for model/skill defaults (default: default)")
    p_create.set_defaults(func=cmd_create)

    # list
    p_list = sub.add_parser("list", help="List all provisioned tenants")
    p_list.set_defaults(func=cmd_list)

    # status
    p_status = sub.add_parser("status", help="Show status for a tenant")
    p_status.add_argument("tenant_id", metavar="TENANT_ID")
    p_status.set_defaults(func=cmd_status)

    # create-demo
    p_demo = sub.add_parser("create-demo", help="Provision 3 demo tenants (legal, medical, ecommerce)")
    p_demo.set_defaults(func=cmd_create_demo)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
