#!/usr/bin/env python3
"""Auto-provision isolated HERMES_HOME profiles for every lunark model.

Reads ``<base_url>/models``, gets the per-model context_length / max_model_len
/ tool_calling / reasoning flags, and writes a config.yaml + .env into a
target directory for each model. Designed so the lunark lineup can change
under us and we just rerun this to get fresh, accurate profiles.

Usage:
    python examples/lunark_provision.py            # default base, /tmp/hermes_<MODEL>
    python examples/lunark_provision.py --root /opt/hermes-profiles
    LUNARK_API_KEY=foo python examples/lunark_provision.py --base https://llm.lunark.ai/v1
"""
from __future__ import annotations
import argparse
import json
import os
import sys
import urllib.request


def fetch_models(base_url: str, api_key: str) -> list[dict]:
    headers = {"User-Agent": "hermes-lunark-provision/1.0"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    req = urllib.request.Request(base_url.rstrip("/") + "/models", headers=headers)
    with urllib.request.urlopen(req, timeout=10) as r:
        payload = json.loads(r.read().decode())
    return payload.get("data", [])


def derive_max_tokens(context_length: int, has_reasoning: bool) -> int:
    """Pick a sensible per-call max_tokens budget.

    Reasoning models need ~2-4x the budget of non-reasoning models because
    a chunk gets eaten by <think> chains. We cap at 8192 since lunark
    backends often reject larger generation budgets.
    """
    if has_reasoning:
        return min(8192, max(2048, context_length // 8))
    return min(4096, max(1024, context_length // 16))


CONFIG_TEMPLATE = """\
# Auto-generated by examples/lunark_provision.py — do not hand edit
model:
  default: {model_id}
  provider: lunark
  base_url: {base_url}
  api_key: {api_key}
  context_length: {context_length}
  max_tokens: {max_tokens}
providers: {{}}
fallback_providers: []
toolsets: [hermes-cli]
agent:
  max_turns: 60
  reasoning_effort: medium
  tool_use_enforcement: auto
"""


def write_profile(root: str, model: dict, base_url: str, api_key: str) -> tuple[str, dict]:
    model_id = model["id"]
    safe_id = model_id  # already filename-safe in practice; otherwise sanitize
    profile_dir = os.path.join(root, f"hermes_{safe_id}")
    os.makedirs(profile_dir, exist_ok=True)

    context_length = int(model.get("context_length") or model.get("max_model_len") or 32768)
    has_reasoning = bool(model.get("reasoning"))
    max_tokens = derive_max_tokens(context_length, has_reasoning)

    config = CONFIG_TEMPLATE.format(
        model_id=model_id,
        base_url=base_url,
        api_key=api_key,
        context_length=context_length,
        max_tokens=max_tokens,
    )
    with open(os.path.join(profile_dir, "config.yaml"), "w") as f:
        f.write(config)
    with open(os.path.join(profile_dir, ".env"), "w") as f:
        f.write(f"LUNARK_API_KEY={api_key}\n")

    return profile_dir, {
        "model_id": model_id,
        "context_length": context_length,
        "max_tokens": max_tokens,
        "tool_calling": bool(model.get("tool_calling")),
        "reasoning": has_reasoning,
        "profile": profile_dir,
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", default=os.environ.get("LUNARK_BASE_URL", "https://llm.lunark.ai/v1"))
    ap.add_argument("--api-key", default=os.environ.get("LUNARK_API_KEY", "vllm-local"))
    ap.add_argument("--root", default="/tmp", help="Root directory for hermes_<MODEL> profiles")
    ap.add_argument("--json", action="store_true", help="Emit JSON summary instead of human format")
    args = ap.parse_args()

    try:
        models = fetch_models(args.base, args.api_key)
    except Exception as e:
        print(f"❌ Failed to fetch {args.base}/models: {type(e).__name__}: {e}", file=sys.stderr)
        sys.exit(1)

    if not models:
        print(f"⚠️  No models returned from {args.base}/models", file=sys.stderr)
        sys.exit(1)

    summaries = []
    for model in models:
        profile_dir, summary = write_profile(args.root, model, args.base, args.api_key)
        summaries.append(summary)

    if args.json:
        print(json.dumps({"base": args.base, "profiles": summaries}, indent=2))
        return

    print(f"\n✅ Provisioned {len(summaries)} lunark profiles under {args.root}/\n")
    print(f"  {'MODEL':24s} {'CTX':>6s} {'MAX_TOK':>8s}  {'TOOL':>4s} {'RSN':>4s}  PROFILE")
    print("  " + "-" * 78)
    for s in summaries:
        print(
            f"  {s['model_id']:24s} {s['context_length']:>6d} {s['max_tokens']:>8d}"
            f"  {'✓' if s['tool_calling'] else '✗':>4s} {'✓' if s['reasoning'] else '✗':>4s}"
            f"  {s['profile']}"
        )
    print()
    print("To use a profile:")
    print(f"  HERMES_HOME={summaries[0]['profile']} hermes chat -q 'hello'")
    print()


if __name__ == "__main__":
    main()
